ТЗ 6
Dari8Kazak/java-kanban pull request #1
Opened 2024-09-22 14:44 UTC by Dari8Kazak

История посещений неограниченна по размеру.
Избавилась от повторных просмотров в истории.

2024-09-22 17:20 UTC, vlolad requested changes
Привет!

Всё хорошо, логика по ТЗ реализована верно. Немного осталось доработать менеджер задач и метод удаления ноды и будет вообще отлично. Всё в комментариях написал

Хорошего вечера!

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryTaskManager.java
>          tasks.clear();
При удалении задач теперь надо удалять их и из истории. Во всех методах с удалением надо добавить вызов remove() из HistroyManager

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        public Node<T> getPrev() {
Для вложенных классов можно и прямой доступ оставить, без геттеров сеттеров. Т.е. будет просто node.next (например) вместо node.getNext()
Если в исходники базовых классов Java посмотришь, вроде того же LinkedList, то это там часто встречается

Но можно геттеры/сеттеры оставить, это на вкус и цвет

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +    private void removeNode(Node<Task> node) {
Не учтена ситуация, когда удаляем единственную ноду. Тогда и head, и tail станут null

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        LinkedList<model.Task> tasks = new LinkedList<>();
Тут можно обычным ArrayList обойтись, который можно упаковать в интерфейс. LinkedList использовать избыточно
`List<Task> tasks = new ArrayList<>();`

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +        LinkedList<model.Task> tasks = new LinkedList<>();
В остальном метод верный, всё отлично

2024-09-22 17:20 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +    private void linkLastObject(Task task) {
Всё верно

2024-09-23 13:52 UTC, Dari8Kazak commented on src/service/InMemoryTaskManager.java
>          tasks.clear();
Во всех методах с удалением  добавлен вызов remove() из HistroyManager

2024-09-23 13:53 UTC, Dari8Kazak commented on src/service/InMemoryHistoryManager.java
> +        public Node<T> getPrev() {
оставлю пока

2024-09-23 14:16 UTC, Dari8Kazak commented on src/service/InMemoryHistoryManager.java
> +    private void removeNode(Node<Task> node) {
+

2024-09-23 14:32 UTC, Dari8Kazak commented on src/service/InMemoryHistoryManager.java
> +        LinkedList<model.Task> tasks = new LinkedList<>();
LinkedList удален

2024-09-23 18:09 UTC, vlolad approved these changes
Привет!

Уже почти хорошо, но удаление задач из истории в основном менеджер задач не сделано. Надо доработать, оставил комментарии

Для проверки можно вручную протестировать код в классе Main с дебагером. Так удобнее смотреть, в каком состоянии находится менеджер и пошагово пройтись по выполнению команд программой

Хорошего вечера!

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
>          tasks.clear();
Не могу с этим поспорить. Только удаление не работает)

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Надо удалить все задачи из истории
P.S. Вообще, по ТЗ метод для удаления всех задач не требуется, его можно полностью убрать

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Нужно удалить задачу с taskId

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Нужно удалить все эпики. Для этого можно использовать цикл и `epics.values()` (как и `subtasks.vaules()`)

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Нужно удалить эпик с epicId

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Нужно удалить все подзадачи. Можно использовать цикл и `subtasks.values()`

2024-09-23 18:09 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
Удаляется задача под id, который равен общему счетчику менеджера. Нужно удалить подзадачу с subTaskId

2024-09-24 12:53 UTC, Dari8Kazak commented on src/service/InMemoryTaskManager.java
> +        historyManager.remove(id);
+

2024-09-25 08:26 UTC, vlolad approved these changes
Привет!

Теперь всё хорошо, принято с:

2024-09-25 08:26 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +    private void removeHistory(Set<Integer> ids) {
Хорошее решение, можно было бы даже в менеджер истории вынести
Плюс ещё пожелание - аргументом метода сделать Collection<Integer>, чтобы можно было и List, и Set передавать, как и вообще любую коллекцию идентификаторов

2024-12-02 14:02 UTC, merged